import type { DbShop, ProductWithShop } from "@/types/database";

const img = (id: number) =>
  `https://images.unsplash.com/photo-${id}?w=600&q=80&auto=format&fit=crop`;

export const MOCK_SHOPS: DbShop[] = [
  {
    id: "m1",
    name: "Gift Studio Tashkent",
    description: "Premium sovg‘alar va qadoqlash. Tez yetkazib berish.",
    city: "Toshkent",
    logo_url: img(1549465220),
    banner_url: img(1513885047091),
    is_approved: true,
    is_featured: true,
    subscription_type: "vip",
    owner_telegram_username: "giftstudio_uz",
  },
  {
    id: "m2",
    name: "Bloom Flowers",
    description: "Yashil o‘simliklar va guldasta — har kun uchun.",
    city: "Samarqand",
    logo_url: img(1490759560239),
    banner_url: img(1462275648994),
    is_approved: true,
    is_featured: true,
    subscription_type: "basic",
    owner_telegram_username: "bloom_flowers",
  },
  {
    id: "m3",
    name: "Craft & Joy",
    description: "Qo‘lda yasalgan aksessuarlar va souvenirlar.",
    city: "Buxoro",
    logo_url: img(1607082349489),
    banner_url: img(1558618666),
    is_approved: true,
    is_featured: false,
    subscription_type: "free",
    owner_telegram_username: "craftjoy_uz",
  },
];

export const MOCK_PRODUCTS: ProductWithShop[] = [
  {
    id: "p1",
    name: "Premium guldasta «Bahor»",
    description: "Tabiiy atirgullar, zamonaviy dizayn.",
    price: 189000,
    image_url: img(1563241527),
    category: "Gullar",
    shop_id: "m2",
    is_active: true,
    created_at: new Date().toISOString(),
    is_featured: true,
    badge: "hot",
    shops: MOCK_SHOPS[1],
  },
  {
    id: "p2",
    name: "Sovg‘a to‘plami «VIP»",
    description: "Shokolad, choy va brend quti.",
    price: 420000,
    image_url: img(1549461026),
    category: "To‘plamlar",
    shop_id: "m1",
    is_active: true,
    created_at: new Date().toISOString(),
    is_featured: true,
    badge: "star",
    shops: MOCK_SHOPS[0],
  },
  {
    id: "p3",
    name: "Tug‘ilgan kun soatlari",
    description: "Minimal dizayn, shaxsiylashtirish mumkin.",
    price: 350000,
    image_url: img(1523275339524),
    category: "Aksessuarlar",
    shop_id: "m3",
    is_active: true,
    created_at: new Date().toISOString(),
    badge: "top",
    shops: MOCK_SHOPS[2],
  },
  {
    id: "p4",
    name: "Tabiiy sham komplekti",
    description: "Lavanda va vanil aromati.",
    price: 125000,
    image_url: img(1608571423902),
    category: "Uy uchun",
    shop_id: "m1",
    is_active: true,
    created_at: new Date().toISOString(),
    shops: MOCK_SHOPS[0],
  },
  {
    id: "p5",
    name: "Mini kaktuslar to‘plami",
    description: "3 ta o‘simlik + keramika idishlar.",
    price: 98000,
    image_url: img(1459410050234),
    category: "O‘simliklar",
    shop_id: "m2",
    is_active: true,
    created_at: new Date().toISOString(),
    badge: "star",
    shops: MOCK_SHOPS[1],
  },
  {
    id: "p6",
    name: "Shaxsiy gravür quti",
    description: "Ism va sana bilan.",
    price: 210000,
    image_url: img(1513519245087),
    category: "Shaxsiylashtirish",
    shop_id: "m3",
    is_active: true,
    created_at: new Date().toISOString(),
    shops: MOCK_SHOPS[2],
  },
  {
    id: "p7",
    name: "Tug‘ilgan kun torti va sham",
    description: "Buyurtma bo‘yicha dizayn.",
    price: 280000,
    image_url: img(1558636428),
    category: "Tug‘ilgan kun",
    shop_id: "m1",
    is_active: true,
    created_at: new Date().toISOString(),
    badge: "star",
    shops: MOCK_SHOPS[0],
  },
];

export const MOCK_CATEGORIES = [
  "Hammasi",
  "Gullar",
  "To‘plamlar",
  "Aksessuarlar",
  "Uy uchun",
  "O‘simliklar",
  "Shaxsiylashtirish",
  "Tug‘ilgan kun",
];
